sudo: required
services: 
  - docker

before_install: 
  - docker build -t freskimaliu/test-react -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true freskimaliu/test-react npm run test

after_success: 
  - docker build -t freskimaliu/multi-client ./client
  - docker build -t freskimaliu/multi-nginx ./nginx
  - docker build -t freskimaliu/multi-server ./server
  - docker build -t freskimaliu/multi-worker ./worker