sudo: required
services: 
  - docker

before_install: 
  - docker build -t freskimaliu/test-react -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true freskimaliu/test-react npm run test

after_success: 
  - docker build -t freskimaliu/multi-client ./client
  - docker build -t freskimaliu/multi-nginx ./nginx
  - docker build -t freskimaliu/multi-server ./server
  - docker build -t freskimaliu/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push freskimaliu/multi-client
  - docker push freskimaliu/multi-nginx
  - docker push freskimaliu/multi-server
  - docker push freskimaliu/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: multi-docker-env
  bucket_name: elasticbeanstalk-us-east-1-250218130509
  bucket_path: multi-docker
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY